const RATE=0.21,CONFIG_KEY="travelExpenseSupabaseConfig_v1";let client=null,expenses=[];
const yen=n=>"¥"+Number(n).toLocaleString(),twd=n=>"NT$"+Math.round(Number(n)*RATE).toLocaleString(),isTopup=e=>e.category==="交通儲值";
const sum=(a,f)=>a.reduce((s,x)=>s+f(x),0),groupBy=(a,k)=>a.reduce((m,x)=>((m[x[k]]||=[]).push(x),m),{});function setStatus(m){document.getElementById("status").textContent=m}
function loadConfig(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"{}")}catch{return {}}}
function saveConfig(){const url=document.getElementById("supabaseUrl").value.trim(),key=document.getElementById("supabaseKey").value.trim();localStorage.setItem(CONFIG_KEY,JSON.stringify({url,key}));connect()}
function connect(){const {url,key}=loadConfig();document.getElementById("supabaseUrl").value=url||"";document.getElementById("supabaseKey").value=key||"";if(!url||!key){setStatus("請先輸入 Supabase Project URL 與 anon/publishable key。");return}client=supabase.createClient(url,key);loadExpenses()}
async function loadExpenses(){setStatus("正在讀取 Supabase...");const {data,error}=await client.from("expenses").select("*").order("date",{ascending:true}).order("created_at",{ascending:true});if(error){setStatus("讀取失敗："+error.message);return}expenses=data||[];setStatus(`已同步 ${expenses.length} 筆資料`);render()}
async function insertRows(rows){if(!client){setStatus("請先設定 Supabase。");return false}const {error}=await client.from("expenses").insert(rows);if(error){setStatus("寫入失敗："+error.message);return false}setStatus(`已寫入 ${rows.length} 筆資料`);await loadExpenses();return true}
function render(){const actual=sum(expenses.filter(e=>!isTopup(e)),e=>Number(e.jpy)),topup=sum(expenses.filter(isTopup),e=>Number(e.jpy));document.getElementById("stats").innerHTML=`<div class="stat"><div class="label">實際消費</div><div class="big">${yen(actual)}</div><div class="label">約 ${twd(actual)}</div></div><div class="stat"><div class="label">含儲值總額</div><div class="big">${yen(actual+topup)}</div><div class="label">約 ${twd(actual+topup)}</div></div><div class="stat"><div class="label">Suica/ICOCA 儲值</div><div class="big">${yen(topup)}</div><div class="label">不列入實際消費</div></div><div class="stat"><div class="label">雲端明細</div><div class="big">${expenses.length}</div><div class="label">Supabase</div></div>`;const byDay=groupBy(expenses,"day");document.getElementById("expenseList").innerHTML=Object.entries(byDay).map(([day,rows])=>{const dayActual=sum(rows.filter(e=>!isTopup(e)),e=>Number(e.jpy));const body=rows.map((e,i)=>`<tr class="data-row" data-search="${[e.date,e.day,e.store,e.category,e.name,e.qty,e.payment,e.note].join(" ").toLowerCase()}"><td>${i+1}</td><td>${e.date}</td><td>${e.store}</td><td>${e.category}</td><td class="name">${e.name}</td><td>${e.qty??""}</td><td class="num">${yen(e.jpy)}</td><td class="num">${twd(e.jpy)}</td><td>${e.payment||""}</td><td>${e.note||""}</td></tr>`).join("");return `<section class="day-section"><h2>${day}｜實際消費 ${yen(dayActual)} / 約 ${twd(dayActual)}</h2><div class="table-wrap"><table><thead><tr><th>#</th><th>日期</th><th>店家</th><th>類別</th><th>商品名稱</th><th>數量</th><th>日幣</th><th>台幣約</th><th>付款</th><th>備註</th></tr></thead><tbody>${body}</tbody></table></div></section>`}).join("");filterRows()}
function filterRows(){const q=document.getElementById("search").value.trim().toLowerCase();document.querySelectorAll(".data-row").forEach(r=>r.classList.toggle("hidden",q&&!r.dataset.search.includes(q)))}
document.getElementById("saveConfig").addEventListener("click",saveConfig);document.getElementById("search").addEventListener("input",filterRows);
document.getElementById("expenseForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);const ok=await insertRows([{date:f.get("date"),day:f.get("day"),store:f.get("store"),category:f.get("category"),name:f.get("name"),qty:f.get("qty")||null,jpy:Number(f.get("jpy")),payment:f.get("payment"),note:f.get("note")}]);if(ok)e.target.reset()});
document.getElementById("bulkForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);const rows=f.get("items").split("\n").map(s=>s.trim()).filter(Boolean).map(line=>{const p=line.split("｜").map(s=>s.trim());return {date:f.get("date"),day:f.get("day"),store:f.get("store"),category:f.get("category"),name:p[0],qty:p[1]||null,jpy:Number(p[2]),payment:f.get("payment"),note:f.get("note")}}).filter(x=>x.name&&Number.isFinite(x.jpy));const ok=await insertRows(rows);if(ok)e.target.reset()});connect();
