const RATE = 0.21;
const EXPENSES = [
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "FamilyMart 關西空港站",
    "category": "超商/餐飲",
    "name": "可可椰子白桃飲料",
    "qty": 1,
    "jpy": 298,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "FamilyMart 關西空港站",
    "category": "超商/餐飲",
    "name": "哈密瓜牛奶",
    "qty": 1,
    "jpy": 290,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "FamilyMart 關西空港站",
    "category": "超商/餐飲",
    "name": "北海道哈密瓜麵包",
    "qty": 2,
    "jpy": 276,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "FamilyMart 關西空港站",
    "category": "超商/餐飲",
    "name": "紅豆丹麥麵包",
    "qty": 2,
    "jpy": 256,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "ICOCA/Suica 儲值",
    "category": "交通儲值",
    "name": "IC卡儲值",
    "qty": 1,
    "jpy": 10000,
    "payment": "現金",
    "note": "儲值，不列入實際消費"
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "KOHYO 森之宮店 15:32",
    "category": "超市",
    "name": "KOHYO 下午收據合計（雞蛋、高麗菜、厚燒玉子等）",
    "qty": "",
    "jpy": 1797,
    "payment": "信用卡/現金",
    "note": "已修正厚燒玉子"
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "KOHYO 森之宮店 22:30",
    "category": "超市",
    "name": "KOHYO 晚上收據合計（西瓜、豬肉、有機豆奶等）",
    "qty": "",
    "jpy": 3154,
    "payment": "信用卡/現金",
    "note": "已修正有機豆奶"
  },
  {
    "date": "2026-07-05",
    "day": "Day 1",
    "store": "唐吉訶德 道頓堀",
    "category": "伴手禮",
    "name": "KitKat、糖果、餅乾等伴手禮",
    "qty": 18,
    "jpy": 16340,
    "payment": "信用卡",
    "note": "免稅，含優惠"
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "LAWSON 祇園花見小路店",
    "category": "超商/餐飲",
    "name": "三色糰子（半價）",
    "qty": 1,
    "jpy": 63,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "LAWSON 祇園花見小路店",
    "category": "超商/餐飲",
    "name": "大阪燒",
    "qty": 1,
    "jpy": 384,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "LAWSON 祇園花見小路店",
    "category": "超商/餐飲",
    "name": "鮪魚美乃滋飯糰",
    "qty": 1,
    "jpy": 289,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "LAWSON 祇園花見小路店",
    "category": "超商/餐飲",
    "name": "牛肉飯糰",
    "qty": 1,
    "jpy": 203,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "LAWSON 祇園花見小路店",
    "category": "超商/餐飲",
    "name": "購物袋",
    "qty": 1,
    "jpy": 5,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "鳴門鯛燒本舖",
    "category": "點心",
    "name": "十勝紅豆鯛魚燒",
    "qty": 1,
    "jpy": 400,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "鳴門鯛燒本舖",
    "category": "點心",
    "name": "卡士達鯛魚燒",
    "qty": 1,
    "jpy": 400,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "清水寺",
    "category": "門票",
    "name": "參拜門票－大人",
    "qty": 1,
    "jpy": 500,
    "payment": "現金",
    "note": "手動新增"
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "清水寺",
    "category": "門票",
    "name": "參拜門票－小孩",
    "qty": 1,
    "jpy": 100,
    "payment": "現金",
    "note": "手動新增"
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "自動販賣機",
    "category": "飲料",
    "name": "飲料",
    "qty": 2,
    "jpy": 220,
    "payment": "現金",
    "note": "兩瓶共 ¥220"
  },
  {
    "date": "2026-07-06",
    "day": "Day 2",
    "store": "KOHYO 森之宮店",
    "category": "超市",
    "name": "KOHYO 收據合計（25項食品/飲料/熟食）",
    "qty": "",
    "jpy": 5227,
    "payment": "信用卡/現金",
    "note": ""
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "Nintendo OSAKA 11:00",
    "category": "玩具/伴手禮",
    "name": "Nintendo 11:00 收據合計（皮克敏、寶可夢、茶包、T恤、毛巾等）",
    "qty": "",
    "jpy": 36487,
    "payment": "信用卡",
    "note": "已確認，另有16:03收據"
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "Nintendo OSAKA 16:03",
    "category": "玩具/伴手禮",
    "name": "Room 系列玩偶（ルーム）",
    "qty": 6,
    "jpy": 8400,
    "payment": "信用卡",
    "note": "獨立發票，不取代11:00"
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "Nintendo OSAKA 16:03",
    "category": "稅金",
    "name": "消費稅 10%",
    "qty": "",
    "jpy": 840,
    "payment": "信用卡",
    "note": "此收據合計 ¥9,240"
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "Pokémon Center Osaka",
    "category": "玩具/伴手禮",
    "name": "寶可夢玩偶",
    "qty": 1,
    "jpy": 2200,
    "payment": "信用卡",
    "note": ""
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "MUJI Grand Front Osaka",
    "category": "生活用品/美妝",
    "name": "MUJI 明細合計（筆袋、BB霜、證件套、UV粉餅、紙袋）",
    "qty": "",
    "jpy": 5260,
    "payment": "信用卡",
    "note": ""
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "JR 森之宮站",
    "category": "交通儲值",
    "name": "Suica 儲值",
    "qty": 1,
    "jpy": 5000,
    "payment": "現金",
    "note": "儲值，不列入實際消費"
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "FamilyMart",
    "category": "超商/餐飲",
    "name": "玉米濃湯／玉米牛奶",
    "qty": 2,
    "jpy": 556,
    "payment": "Suica",
    "note": ""
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "LIFE Central Square 難波店",
    "category": "超市",
    "name": "LIFE 收據合計（炸魷魚、洋芋片、豆皮壽司、OIKOS、拉麵等）",
    "qty": "",
    "jpy": 6093,
    "payment": "信用卡",
    "note": "洋芋片、豆皮壽司已確認"
  },
  {
    "date": "2026-07-07",
    "day": "Day 3",
    "store": "唐吉訶德/免稅店",
    "category": "伴手禮",
    "name": "干貝、Pikmin軟糖、茶包、烏龍麵、零食等",
    "qty": "",
    "jpy": 19168,
    "payment": "信用卡",
    "note": "可後續再拆更細"
  },
  {
    "date": "2026-07-08",
    "day": "Day 4",
    "store": "大國藥妝",
    "category": "藥妝/保健",
    "name": "大國藥妝免稅收據合計（Za、眼藥水、Ipo Care、GABA、藍莓保健錠等）",
    "qty": 31,
    "jpy": 58338,
    "payment": "信用卡",
    "note": "EVE已移除；已確認"
  },
  {
    "date": "2026-07-08",
    "day": "Day 4",
    "store": "一蘭拉麵",
    "category": "餐飲",
    "name": "店內用餐",
    "qty": "",
    "jpy": 4200,
    "payment": "信用卡",
    "note": ""
  },
  {
    "date": "2026-07-08",
    "day": "Day 4",
    "store": "一蘭伴手禮",
    "category": "伴手禮",
    "name": "一蘭杯麵",
    "qty": 2,
    "jpy": 1080,
    "payment": "現金/信用卡",
    "note": ""
  },
  {
    "date": "2026-07-08",
    "day": "Day 4",
    "store": "KOHYO 森之宮店",
    "category": "超市",
    "name": "KOHYO 收據合計（15項：冰、茶、糰子、炸豬排、牛奶、吐司等）",
    "qty": 15,
    "jpy": 3765,
    "payment": "信用卡/現金",
    "note": ""
  },
  {
    "date": "2026-07-09",
    "day": "Day 5",
    "store": "平等院",
    "category": "門票",
    "name": "大人門票",
    "qty": 1,
    "jpy": 700,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-09",
    "day": "Day 5",
    "store": "平等院",
    "category": "門票",
    "name": "學生門票",
    "qty": 1,
    "jpy": 400,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-09",
    "day": "Day 5",
    "store": "蛸Q 宇治",
    "category": "點心",
    "name": "宇治抹茶霜淇淋",
    "qty": 2,
    "jpy": 1000,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-09",
    "day": "Day 5",
    "store": "伊藤久右衛門",
    "category": "伴手禮/點心",
    "name": "抹茶麻糬、抹茶蕨餅",
    "qty": "",
    "jpy": 939,
    "payment": "現金",
    "note": ""
  },
  {
    "date": "2026-07-09",
    "day": "Day 5",
    "store": "JR 森之宮站",
    "category": "交通儲值",
    "name": "Suica 儲值",
    "qty": 1,
    "jpy": 2000,
    "payment": "現金",
    "note": "儲值，不列入實際消費"
  }
];
