create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  day text not null,
  store text not null,
  category text not null,
  name text not null,
  qty numeric,
  jpy numeric not null check (jpy >= 0),
  payment text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.expenses enable row level security;

create policy "anon can read expenses"
on public.expenses for select
to anon
using (true);

create policy "anon can insert expenses"
on public.expenses for insert
to anon
with check (true);
